# Generated by Django 5.2.1 on 2025-06-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_userfollows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='uploader',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
